### ISSUE TITLE
Missing /support/pipeline.py

### ISSUE THREAD

**Issue by polisen** [calvdee/end-to-end-lead-scoring#1]
Hey - I'm exploring your god-tier guide but was disappointed to discover that the support-file pipeline.py is missing which entails errors in experiment 2.0. Could you commit it please. Cheers. Also - well done. It's incredibly illuminating.

**Comment by polisen** [comment]
Never mind - I see what you did. You put it in the experiment imports. Maybe the import should be removed - `from support.pipeline import get_pipeline, get_feature_names_for_pipeline `on line `69` of `./notebooks/2.0-experiment-1-baseline-vs-ml.ipynb`

**Comment by wyieborn** [comment]
This is a great notebook you provided. Just a small thing if anyone is using this for learning purpose. you might get stuck into above problem mentioned by polisen. this could be solved by just removing the import. another thing when evaluating models after BernoulliNB the evaluatemodel function used in '2.0-experiment-1-baseline-vs-ml.ipynb' is missing the scorer parameter just before the pipeline param. That should solve it.
